In [1]:
#Import CSV File
import pandas as pd
from sklearn.model_selection import train_test_split as tts
match_data = pd.read_csv('finalDataset.csv')
match_data.head()

,Team 1_Afghanistan,Team 1_Australia,Team 1_Bangladesh,Team 1_Bermuda,Team 1_Canada,Team 1_East Africa,Team 1_England,Team 1_Hong Kong,Team 1_India,Team 1_Ireland,...,Winner_New Zealand,Winner_P.N.G.,Winner_Pakistan,Winner_Scotland,Winner_South Africa,Winner_Sri Lanka,Winner_U.A.E.,Winner_U.S.A.,Winner_West Indies,Winner_Zimbabwe
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [2]:
#Display Columns
for i, feature in enumerate(list(match_data.columns)):
    print (i, feature)

0 Team 1_Afghanistan
1 Team 1_Australia
2 Team 1_Bangladesh
3 Team 1_Bermuda
4 Team 1_Canada
5 Team 1_East Africa
6 Team 1_England
7 Team 1_Hong Kong
8 Team 1_India
9 Team 1_Ireland
10 Team 1_Kenya
11 Team 1_Namibia
12 Team 1_Netherlands
13 Team 1_New Zealand
14 Team 1_P.N.G.
15 Team 1_Pakistan
16 Team 1_Scotland
17 Team 1_South Africa
18 Team 1_Sri Lanka
19 Team 1_U.A.E.
20 Team 1_U.S.A.
21 Team 1_West Indies
22 Team 1_Zimbabwe
23 Team 2_Afghanistan
24 Team 2_Australia
25 Team 2_Bangladesh
26 Team 2_Bermuda
27 Team 2_Canada
28 Team 2_East Africa
29 Team 2_England
30 Team 2_Hong Kong
31 Team 2_India
32 Team 2_Ireland
33 Team 2_Kenya
34 Team 2_Namibia
35 Team 2_Netherlands
36 Team 2_New Zealand
37 Team 2_P.N.G.
38 Team 2_Pakistan
39 Team 2_Scotland
40 Team 2_South Africa
41 Team 2_Sri Lanka
42 Team 2_U.A.E.
43 Team 2_U.S.A.
44 Team 2_West Indies
45 Team 2_Zimbabwe
46 Ground_Aberdeen
47 Ground_Abu Dhabi
48 Ground_Adelaide
49 Ground_Ahmedabad
50 Ground_Albion
51 Ground_Albury
52 Ground_Amritsar
53 Ground_Amstelveen
54 Ground_Auckland
55 Ground_Ayr
56 Ground_Ballarat
57 Ground_Basseterre
58 Ground_Belfast
59 Ground_Bengaluru
60 Ground_Benoni
61 Ground_Berri
62 Ground_Birmingham
63 Ground_Bloemfontein
64 Ground_Bogra
65 Ground_Bridgetown
66 Ground_Brisbane
67 Ground_Bristol
68 Ground_Bulawayo
69 Ground_Cairns
70 Ground_Canberra
71 Ground_Canterbury
72 Ground_Cape Town
73 Ground_Cardiff
74 Ground_Castries
75 Ground_Centurion
76 Ground_Chandigarh
77 Ground_Chelmsford
78 Ground_Chennai
79 Ground_Chester
80 Ground_Chittagong
81 Ground_Christchurch
82 Ground_Colombo
83 Ground_Cuttack
84 Ground_Dambulla
85 Ground_Darwin
86 Ground_Delhi
87 Ground_Derby
88 Ground_Devonport
89 Ground_Dhaka
90 Ground_Dharamsala
91 Ground_Dubai
92 Ground_Dublin
93 Ground_Dunedin
94 Ground_Durban
95 Ground_East London
96 Ground_Edinburgh
97 Ground_Faisalabad
98 Ground_Faridabad
99 Ground_Fatullah
100 Ground_Galle
101 Ground_Georgetown
102 Ground_Glasgow
103 Ground_Greater Noida
104 Ground_Gros Islet
105 Ground_Gujranwala
106 Ground_Guwahati
107 Ground_Gwalior
108 Ground_Hambantota
109 Ground_Hamilton
110 Ground_Harare
111 Ground_Hobart
112 Ground_Hove
113 Ground_Hyderabad
114 Ground_ICCA Dubai
115 Ground_Indore
116 Ground_Jaipur
117 Ground_Jalandhar
118 Ground_Jamshedpur
119 Ground_Jodhpur
120 Ground_Johannesburg
121 Ground_Kandy
122 Ground_Kanpur
123 Ground_Karachi
124 Ground_Khulna
125 Ground_Kimberley
126 Ground_King City
127 Ground_Kingston
128 Ground_Kingstown
129 Ground_Kochi
130 Ground_Kolkata
131 Ground_Kuala Lumpur
132 Ground_Kwekwe
133 Ground_Lahore
134 Ground_Launceston
135 Ground_Leeds
136 Ground_Leicester
137 Ground_Lincoln
138 Ground_Lord's
139 Ground_Lucknow
140 Ground_Manchester
141 Ground_Margao
142 Ground_Melbourne
143 Ground_Mohali
144 Ground_Mombasa
145 Ground_Mong Kok
146 Ground_Moratuwa
147 Ground_Mount Maunganui
148 Ground_Multan
149 Ground_Mumbai
150 Ground_Nagpur
151 Ground_Nairobi
152 Ground_Napier
153 Ground_Nelson
154 Ground_New Delhi
155 Ground_New Plymouth
156 Ground_North Sound
157 Ground_Northampton
158 Ground_Nottingham
159 Ground_Paarl
160 Ground_Pallekele
161 Ground_Patna
162 Ground_Perth
163 Ground_Peshawar
164 Ground_Pietermaritzburg
165 Ground_Port Elizabeth
166 Ground_Port Moresby
167 Ground_Port of Spain
168 Ground_Potchefstroom
169 Ground_Providence
170 Ground_Pune
171 Ground_Queenstown
172 Ground_Quetta
173 Ground_Rajkot
174 Ground_Ranchi
175 Ground_Rawalpindi
176 Ground_Roseau
177 Ground_Rotterdam
178 Ground_Sahiwal
179 Ground_Sargodha
180 Ground_Scarborough
181 Ground_Schiedam
182 Ground_Sharjah
183 Ground_Sheikhupura
184 Ground_Sialkot
185 Ground_Singapore
186 Ground_Southampton
187 Ground_Srinagar
188 Ground_St George's
189 Ground_St John's
190 Ground_Swansea
191 Ground_Sydney
192 Ground_Tangier
193 Ground_Taunton
194 Ground_Taupo
195 Ground_The Hague
196 Ground_The Oval
197 Ground_Thiruvananthapuram
198 Ground_Toronto
199 Ground_Townsville
200 Ground_Tunbridge Wells
201 Ground_Vadodara
202 Ground_Vijayawada
203 Ground_Visakhapatnam
204 Ground_Wellington
205 Ground_Whangarei
206 Ground_Worcester
207 Innings_Team1_First
208 Innings_Team1_Second
209 Innings_Team2_First
210 Innings_Team2_Second
211 Venue_Team1_Away
212 Venue_Team1_Home
213 Venue_Team1_Neutral
214 Venue_Team2_Away
215 Venue_Team2_Home
216 Venue_Team2_Neutral
217 Winner_Afghanistan
218 Winner_Australia
219 Winner_Bangladesh
220 Winner_Bermuda
221 Winner_Canada
222 Winner_East Africa
223 Winner_England
224 Winner_Hong Kong
225 Winner_India
226 Winner_Ireland
227 Winner_Kenya
228 Winner_Namibia
229 Winner_Netherlands
230 Winner_New Zealand
231 Winner_P.N.G.
232 Winner_Pakistan
233 Winner_Scotland
234 Winner_South Africa
235 Winner_Sri Lanka
236 Winner_U.A.E.
237 Winner_U.S.A.
238 Winner_West Indies
239 Winner_Zimbabwe

In [3]:
#Separation into Feature Set & Target Set

target_cols = match_data.columns[217:240]
feature_cols = match_data.columns[0:217]

print(target_cols)
print(feature_cols)

target_set = match_data[target_cols]
feature_set = match_data[feature_cols]

print(len(target_set))
print(len(feature_set))

Index(['Winner_Afghanistan', 'Winner_Australia', 'Winner_Bangladesh',
       'Winner_Bermuda', 'Winner_Canada', 'Winner_East Africa',
       'Winner_England', 'Winner_Hong Kong', 'Winner_India', 'Winner_Ireland',
       'Winner_Kenya', 'Winner_Namibia', 'Winner_Netherlands',
       'Winner_New Zealand', 'Winner_P.N.G.', 'Winner_Pakistan',
       'Winner_Scotland', 'Winner_South Africa', 'Winner_Sri Lanka',
       'Winner_U.A.E.', 'Winner_U.S.A.', 'Winner_West Indies',
       'Winner_Zimbabwe'],
      dtype='object')
Index(['Team 1_Afghanistan', 'Team 1_Australia', 'Team 1_Bangladesh',
       'Team 1_Bermuda', 'Team 1_Canada', 'Team 1_East Africa',
       'Team 1_England', 'Team 1_Hong Kong', 'Team 1_India', 'Team 1_Ireland',
       ...
       'Innings_Team1_First', 'Innings_Team1_Second', 'Innings_Team2_First',
       'Innings_Team2_Second', 'Venue_Team1_Away', 'Venue_Team1_Home',
       'Venue_Team1_Neutral', 'Venue_Team2_Away', 'Venue_Team2_Home',
       'Venue_Team2_Neutral'],
      dtype='object', length=217)
7494
7494

In [4]:
#Splitting Into Training & Testing Datasets
X = feature_set
Y = target_set
X_train, X_test, Y_train, Y_test = tts(X, Y, test_size=0.25)
print(len(X_train))
print(len(Y_train))

5620
5620

In [5]:
#Decision Tree Classifier 1

from sklearn import tree
DTclf = tree.DecisionTreeClassifier()
DTclf.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [6]:
predicted = DTclf.predict(X_test)
predicted

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [7]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test, predicted))

0.544290288154

In [9]:
train_prediction = DTclf.predict(X_train)
accuracy_score(Y_train, train_prediction)

0.79199288256227762

In [10]:
#Hash Indexing Teams 1

ourTeams_1 = {}
for i,teams in enumerate(list(match_data.columns)):
    if i==23:
        break
    teamName = str(teams)
    teamName = teamName.split("Team 1_", 1)[-1]
    ourTeams_1[teamName] = i
print(ourTeams_1)

{'Hong Kong': 7, 'South Africa': 17, 'Sri Lanka': 18, 'P.N.G.': 14, 'Pakistan': 15, 'Ireland': 9, 'Australia': 1, 'Kenya': 10, 'Namibia': 11, 'Bangladesh': 2, 'New Zealand': 13, 'England': 6, 'Canada': 4, 'West Indies': 21, 'U.A.E.': 19, 'Afghanistan': 0, 'U.S.A.': 20, 'Zimbabwe': 22, 'East Africa': 5, 'India': 8, 'Bermuda': 3, 'Netherlands': 12, 'Scotland': 16}

In [11]:
#Hash Indexing Teams 2

ourTeams_2 = {}
for i,teams in enumerate(list(match_data.columns)):
    if i<23:
        continue
    if i==46:
        break
    teamName = str(teams)
    teamName = teamName.split("Team 2_", 1)[-1]
    ourTeams_2[teamName] = i
print(ourTeams_2)

{'Hong Kong': 30, 'South Africa': 40, 'Sri Lanka': 41, 'P.N.G.': 37, 'Pakistan': 38, 'Ireland': 32, 'Australia': 24, 'Kenya': 33, 'Namibia': 34, 'Bangladesh': 25, 'New Zealand': 36, 'England': 29, 'Canada': 27, 'West Indies': 44, 'U.A.E.': 42, 'Afghanistan': 23, 'U.S.A.': 43, 'Zimbabwe': 45, 'East Africa': 28, 'India': 31, 'Bermuda': 26, 'Netherlands': 35, 'Scotland': 39}

In [12]:
#Hash Indexing Grounds & Innings

ourGrounds = {}
for i,grounds in enumerate(list(match_data.columns)):
    if i<46:
        continue
    if i==207:
        break
    groundName = str(grounds)
    groundName = groundName.split("Ground_", 1)[-1]
    ourGrounds[groundName] = i
print(ourGrounds)
print("\n")
ourInnings = {'Team1_1Inning': 207, 'Team1_2Inning': 208, 'Team2_1Inning': 209, 'Team2_2Inning': 210}
print(ourInnings)
print("\n")
ourVenues = {'Team1_Away': 211, 'Team1_Home': 212, 'Team1_Neutral': 213, 'Team2_Away': 214, 'Team2_Home': 215, 'Team2_Neutral': 216}
print(ourVenues)

{'Bengaluru': 59, 'Bogra': 64, 'Chelmsford': 77, 'Basseterre': 57, 'Singapore': 185, 'New Plymouth': 155, 'Faridabad': 98, 'East London': 95, 'Thiruvananthapuram': 197, 'Nelson': 153, 'Canberra': 70, "St John's": 189, "Lord's": 138, 'New Delhi': 154, 'Perth': 162, 'Leeds': 135, 'Berri': 61, 'Vadodara': 201, 'Kwekwe': 132, 'Taupo': 194, 'Greater Noida': 103, 'Queenstown': 171, 'Dublin': 92, 'Cardiff': 73, 'Indore': 115, 'Nagpur': 150, 'Napier': 152, 'Port of Spain': 167, 'Jaipur': 116, 'Vijayawada': 202, 'Bridgetown': 65, 'Rawalpindi': 175, 'Dhaka': 89, 'Sahiwal': 178, 'Adelaide': 48, 'Srinagar': 187, 'Rajkot': 173, 'Kochi': 129, 'Lincoln': 137, 'Pallekele': 160, "St George's": 188, 'Kanpur': 122, 'Benoni': 60, 'Manchester': 140, 'King City': 126, 'Derby': 87, 'Roseau': 176, 'Gujranwala': 105, 'Schiedam': 181, 'The Oval': 196, 'Fatullah': 99, 'Swansea': 190, 'Tunbridge Wells': 200, 'Christchurch': 81, 'Margao': 141, 'Kandy': 121, 'Chester': 79, 'Amstelveen': 53, 'Kimberley': 125, 'Colombo': 82, 'Chittagong': 80, 'Multan': 148, 'Ayr': 55, 'Amritsar': 52, 'North Sound': 156, 'Dambulla': 84, 'Centurion': 75, 'Gros Islet': 104, 'Gwalior': 107, 'Paarl': 159, 'Mombasa': 144, 'Aberdeen': 46, 'Jalandhar': 117, 'Mount Maunganui': 147, 'Pune': 170, 'Leicester': 136, 'ICCA Dubai': 114, 'Wellington': 204, 'Ranchi': 174, 'Brisbane': 66, 'Melbourne': 142, 'Hamilton': 109, 'Bloemfontein': 63, 'Sargodha': 179, 'Nottingham': 158, 'The Hague': 195, 'Pietermaritzburg': 164, 'Bulawayo': 68, 'Tangier': 192, 'Kingstown': 128, 'Harare': 110, 'Ahmedabad': 49, 'Dunedin': 93, 'Kolkata': 130, 'Galle': 100, 'Guwahati': 106, 'Patna': 161, 'Visakhapatnam': 203, 'Auckland': 54, 'Moratuwa': 146, 'Chennai': 78, 'Kuala Lumpur': 131, 'Jodhpur': 119, 'Port Elizabeth': 165, 'Taunton': 193, 'Mong Kok': 145, 'Sharjah': 182, 'Dharamsala': 90, 'Glasgow': 102, 'Lucknow': 139, 'Karachi': 123, 'Hambantota': 108, 'Birmingham': 62, 'Sialkot': 184, 'Sheikhupura': 183, 'Townsville': 199, 'Mumbai': 149, 'Worcester': 206, 'Albion': 50, 'Cairns': 69, 'Sydney': 191, 'Cuttack': 83, 'Quetta': 172, 'Hobart': 111, 'Castries': 74, 'Southampton': 186, 'Potchefstroom': 168, 'Whangarei': 205, 'Providence': 169, 'Peshawar': 163, 'Darwin': 85, 'Dubai': 91, 'Khulna': 124, 'Abu Dhabi': 47, 'Cape Town': 72, 'Ballarat': 56, 'Hyderabad': 113, 'Johannesburg': 120, 'Devonport': 88, 'Toronto': 198, 'Belfast': 58, 'Durban': 94, 'Kingston': 127, 'Lahore': 133, 'Nairobi': 151, 'Canterbury': 71, 'Bristol': 67, 'Albury': 51, 'Northampton': 157, 'Delhi': 86, 'Jamshedpur': 118, 'Rotterdam': 177, 'Chandigarh': 76, 'Mohali': 143, 'Hove': 112, 'Port Moresby': 166, 'Launceston': 134, 'Georgetown': 101, 'Edinburgh': 96, 'Scarborough': 180, 'Faisalabad': 97}


{'Team2_1Inning': 209, 'Team2_2Inning': 210, 'Team1_2Inning': 208, 'Team1_1Inning': 207}


{'Team1_Neutral': 213, 'Team2_Away': 214, 'Team1_Home': 212, 'Team1_Away': 211, 'Team2_Neutral': 216, 'Team2_Home': 215}

In [13]:
#Hash Indexing the Target Winners

winnerIndex = {}
counter = 0
for i,teams in enumerate(list(match_data.columns)):
    if i<217:
        continue
    
    teamName = str(teams)
    teamName = teamName.split("Winner_", 1)[-1]
    winnerIndex[teamName] = counter
    counter+=1
print(winnerIndex)

{'Hong Kong': 7, 'South Africa': 17, 'Sri Lanka': 18, 'P.N.G.': 14, 'Pakistan': 15, 'Ireland': 9, 'Australia': 1, 'Kenya': 10, 'Namibia': 11, 'Bangladesh': 2, 'New Zealand': 13, 'England': 6, 'Canada': 4, 'West Indies': 21, 'U.A.E.': 19, 'Afghanistan': 0, 'U.S.A.': 20, 'Zimbabwe': 22, 'East Africa': 5, 'India': 8, 'Bermuda': 3, 'Netherlands': 12, 'Scotland': 16}

In [14]:
#Running Prediction in Detailed Manner

inputPrediction = [0]*217
#print(inputPrediction)
t1 = 'India'
t2 = 'Pakistan'
ground = "Mumbai"
inningsTeam1 = "Team1_2Inning"
inningsTeam2 = "Team2_1Inning"
venueTeam1 = 'Team1_Home'
venueTeam2 = 'Team2_Away'
inputPrediction[ourTeams_1[t1]] = 1
inputPrediction[ourTeams_2[t2]] = 1
inputPrediction[ourGrounds[ground]] = 1
inputPrediction[ourInnings[inningsTeam1]] = 1
inputPrediction[ourInnings[inningsTeam2]] = 1
inputPrediction[ourVenues[venueTeam1]] = 1
inputPrediction[ourVenues[venueTeam2]] = 1
#print(inputPrediction)
print("\n\n\n")

#Running Predictions

ourPrediction = DTclf.predict([inputPrediction])
print(ourPrediction)

indexTeam1 = winnerIndex[t1]
indexTeam2 = winnerIndex[t2]
if ourPrediction[0][indexTeam1] == 1:
    print("Winner:",t1)
elif ourPrediction[0][indexTeam2] == 1:
    print("Winner:",t2)
else:
    print("Decision Tree Classifier Can't Predict for this match reliably!")

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.
   0.  0.  0.  0.  0.]]
Winner: Pakistan