In [1]:
#Import CSV File
import pandas as pd
from sklearn.model_selection import train_test_split as tts
match_data = pd.read_csv('finalDataset.csv')
match_data.head()

,Team 1_Afghanistan,Team 1_Africa XI,Team 1_Asia XI,Team 1_Australia,Team 1_Bangladesh,Team 1_Bermuda,Team 1_Canada,Team 1_England,Team 1_Hong Kong,Team 1_India,...,Winner_P.N.G.,Winner_Pakistan,Winner_Scotland,Winner_South Africa,Winner_Sri Lanka,Winner_U.A.E.,Winner_West Indies,Winner_Zimbabwe,Winner_no result,Winner_tied
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [2]:
#Display Columns
for i, feature in enumerate(list(match_data.columns)):
    print (i, feature)

0 Team 1_Afghanistan
1 Team 1_Africa XI
2 Team 1_Asia XI
3 Team 1_Australia
4 Team 1_Bangladesh
5 Team 1_Bermuda
6 Team 1_Canada
7 Team 1_England
8 Team 1_Hong Kong
9 Team 1_India
10 Team 1_Ireland
11 Team 1_Kenya
12 Team 1_Namibia
13 Team 1_Netherlands
14 Team 1_New Zealand
15 Team 1_P.N.G.
16 Team 1_Pakistan
17 Team 1_Scotland
18 Team 1_South Africa
19 Team 1_Sri Lanka
20 Team 1_U.A.E.
21 Team 1_West Indies
22 Team 1_Zimbabwe
23 Team 2_Afghanistan
24 Team 2_Asia XI
25 Team 2_Australia
26 Team 2_Bangladesh
27 Team 2_Bermuda
28 Team 2_Canada
29 Team 2_England
30 Team 2_Hong Kong
31 Team 2_ICC World XI
32 Team 2_India
33 Team 2_Ireland
34 Team 2_Kenya
35 Team 2_Namibia
36 Team 2_Netherlands
37 Team 2_New Zealand
38 Team 2_P.N.G.
39 Team 2_Pakistan
40 Team 2_Scotland
41 Team 2_South Africa
42 Team 2_Sri Lanka
43 Team 2_U.A.E.
44 Team 2_U.S.A.
45 Team 2_West Indies
46 Team 2_Zimbabwe
47 Ground_Aberdeen
48 Ground_Abu Dhabi
49 Ground_Adelaide
50 Ground_Ahmedabad
51 Ground_Amstelveen
52 Ground_Auckland
53 Ground_Ayr
54 Ground_Basseterre
55 Ground_Belfast
56 Ground_Bengaluru
57 Ground_Benoni
58 Ground_Birmingham
59 Ground_Bloemfontein
60 Ground_Bogra
61 Ground_Bridgetown
62 Ground_Brisbane
63 Ground_Bristol
64 Ground_Bulawayo
65 Ground_Cairns
66 Ground_Canberra
67 Ground_Canterbury
68 Ground_Cape Town
69 Ground_Cardiff
70 Ground_Centurion
71 Ground_Chandigarh
72 Ground_Chennai
73 Ground_Chester-le-Street
74 Ground_Chittagong
75 Ground_Christchurch
76 Ground_Colombo (PSS)
77 Ground_Colombo (RPS)
78 Ground_Colombo (SSC)
79 Ground_Cuttack
80 Ground_Dambulla
81 Ground_Darwin
82 Ground_Delhi
83 Ground_Dhaka
84 Ground_Dharamsala
85 Ground_Dubai (DSC)
86 Ground_Dublin
87 Ground_Dublin (Malahide)
88 Ground_Dunedin
89 Ground_Durban
90 Ground_East London
91 Ground_Edinburgh
92 Ground_Faisalabad
93 Ground_Faridabad
94 Ground_Fatullah
95 Ground_Galle
96 Ground_Georgetown
97 Ground_Glasgow
98 Ground_Greater Noida
99 Ground_Gros Islet
100 Ground_Gujranwala
101 Ground_Guwahati
102 Ground_Gwalior
103 Ground_Hambantota
104 Ground_Hamilton
105 Ground_Harare
106 Ground_Hobart
107 Ground_Hyderabad (Deccan)
108 Ground_Hyderabad (Sind)
109 Ground_ICCA Dubai
110 Ground_Indore
111 Ground_Jaipur
112 Ground_Jamshedpur
113 Ground_Jodhpur
114 Ground_Johannesburg
115 Ground_Kandy
116 Ground_Kanpur
117 Ground_Karachi
118 Ground_Khulna
119 Ground_Kimberley
120 Ground_King City (NW)
121 Ground_Kingston
122 Ground_Kingstown
123 Ground_Kochi
124 Ground_Kolkata
125 Ground_Kuala Lumpur
126 Ground_Kwekwe
127 Ground_Lahore
128 Ground_Leeds
129 Ground_Lincoln
130 Ground_Lord's
131 Ground_Manchester
132 Ground_Margao
133 Ground_Melbourne
134 Ground_Melbourne (Docklands)
135 Ground_Mohali
136 Ground_Mombasa
137 Ground_Mong Kok
138 Ground_Mount Maunganui
139 Ground_Multan
140 Ground_Mumbai
141 Ground_Mumbai (BS)
142 Ground_Nagpur
143 Ground_Nairobi
144 Ground_Nairobi (Gym)
145 Ground_Nairobi (Jaff)
146 Ground_Nairobi (Ruaraka)
147 Ground_Napier
148 Ground_Nelson
149 Ground_North Sound
150 Ground_Nottingham
151 Ground_Paarl
152 Ground_Pallekele
153 Ground_Perth
154 Ground_Peshawar
155 Ground_Pietermaritzburg
156 Ground_Port Elizabeth
157 Ground_Port Moresby
158 Ground_Port of Spain
159 Ground_Potchefstroom
160 Ground_Providence
161 Ground_Pune
162 Ground_Queenstown
163 Ground_Rajkot
164 Ground_Ranchi
165 Ground_Rawalpindi
166 Ground_Roseau
167 Ground_Rotterdam
168 Ground_Schiedam
169 Ground_Sharjah
170 Ground_Sheikhupura
171 Ground_Singapore
172 Ground_Southampton
173 Ground_St George's
174 Ground_St John's
175 Ground_Sydney
176 Ground_Tangier
177 Ground_Taupo
178 Ground_The Hague
179 Ground_The Oval
180 Ground_Toronto
181 Ground_Townsville
182 Ground_Vadodara
183 Ground_Vijayawada
184 Ground_Visakhapatnam
185 Ground_Wellington
186 Ground_Whangarei
187 Margin_Winner1stInning
188 Margin_Winner2ndInning
189 Winner_Afghanistan
190 Winner_Africa XI
191 Winner_Asia XI
192 Winner_Australia
193 Winner_Bangladesh
194 Winner_Bermuda
195 Winner_Canada
196 Winner_England
197 Winner_Hong Kong
198 Winner_ICC World XI
199 Winner_India
200 Winner_Ireland
201 Winner_Kenya
202 Winner_Netherlands
203 Winner_New Zealand
204 Winner_P.N.G.
205 Winner_Pakistan
206 Winner_Scotland
207 Winner_South Africa
208 Winner_Sri Lanka
209 Winner_U.A.E.
210 Winner_West Indies
211 Winner_Zimbabwe
212 Winner_no result
213 Winner_tied

In [3]:
#Separation into Feature Set & Target Set

target_cols = match_data.columns[189:214]
feature_cols = match_data.columns[0:189]

target_set = match_data[target_cols]
feature_set = match_data[feature_cols]

print(len(target_set))
print(len(feature_set))

2398
2398

In [4]:
#Splitting Into Training & Testing Datasets
X = feature_set
Y = target_set
X_train, X_test, Y_train, Y_test = tts(X, Y, test_size=0.25)
print(len(X_train))
print(len(Y_train))

1798
1798

In [5]:
#Decision Tree Classifier 1

from sklearn import tree
DTclf1 = tree.DecisionTreeClassifier()
DTclf1.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [6]:
predicted = DTclf1.predict(X_test)
predicted

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [7]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test, predicted))

0.55

In [9]:
train_prediction = DTclf1.predict(X_train)
accuracy_score(Y_train, train_prediction)

0.84760845383759731

In [10]:
#Hash Indexing Teams 1

ourTeams_1 = {}
for i,teams in enumerate(list(match_data.columns)):
    if i==23:
        break
    teamName = str(teams)
    teamName = teamName.split("Team 1_", 1)[-1]
    ourTeams_1[teamName] = i
print(ourTeams_1)

{'Australia': 3, 'Scotland': 17, 'Canada': 6, 'Bermuda': 5, 'West Indies': 21, 'Namibia': 12, 'England': 7, 'Bangladesh': 4, 'Africa XI': 1, 'India': 9, 'Asia XI': 2, 'South Africa': 18, 'Ireland': 10, 'Afghanistan': 0, 'Pakistan': 16, 'Netherlands': 13, 'Zimbabwe': 22, 'New Zealand': 14, 'U.A.E.': 20, 'Hong Kong': 8, 'Kenya': 11, 'P.N.G.': 15, 'Sri Lanka': 19}

In [11]:
#Hash Indexing Teams 2

ourTeams_2 = {}
for i,teams in enumerate(list(match_data.columns)):
    if i<23:
        continue
    if i==47:
        break
    teamName = str(teams)
    teamName = teamName.split("Team 2_", 1)[-1]
    ourTeams_2[teamName] = i
print(ourTeams_2)

{'Australia': 25, 'Scotland': 40, 'Canada': 28, 'Bermuda': 27, 'West Indies': 45, 'Namibia': 35, 'ICC World XI': 31, 'England': 29, 'Bangladesh': 26, 'India': 32, 'Asia XI': 24, 'U.S.A.': 44, 'South Africa': 41, 'Ireland': 33, 'Afghanistan': 23, 'Pakistan': 39, 'Netherlands': 36, 'Zimbabwe': 46, 'New Zealand': 37, 'U.A.E.': 43, 'Hong Kong': 30, 'Kenya': 34, 'P.N.G.': 38, 'Sri Lanka': 42}

In [12]:
#Hash Indexing Grounds & Innings

ourGrounds = {}
for i,grounds in enumerate(list(match_data.columns)):
    if i<47:
        continue
    if i==187:
        break
    groundName = str(grounds)
    groundName = groundName.split("Ground_", 1)[-1]
    ourGrounds[groundName] = i
print(ourGrounds)
print("\n\n")
ourInnings = {'1': 187, '2': 188}
print(ourInnings)

{'Khulna': 118, 'Edinburgh': 91, 'Basseterre': 54, 'Delhi': 82, 'Singapore': 171, 'Bristol': 63, 'Napier': 147, 'Glasgow': 97, 'Margao': 132, 'Amstelveen': 51, 'Jaipur': 111, 'Kingston': 121, 'Paarl': 151, 'Kochi': 123, 'Johannesburg': 114, 'Pune': 161, 'Georgetown': 96, 'Rajkot': 163, 'Hamilton': 104, 'Colombo (RPS)': 77, 'Multan': 139, 'Benoni': 57, 'Abu Dhabi': 48, 'Gros Islet': 99, 'Centurion': 70, 'Townsville': 181, 'Christchurch': 75, 'Toronto': 180, 'Canterbury': 67, "St George's": 173, 'Faridabad': 93, 'Lincoln': 129, 'Ayr': 53, 'Harare': 105, 'Dublin': 86, 'Dharamsala': 84, 'Kingstown': 122, "St John's": 174, 'Ahmedabad': 50, 'Greater Noida': 98, 'Ranchi': 164, 'Mohali': 135, 'Tangier': 176, 'Belfast': 55, 'Vijayawada': 183, 'Wellington': 185, 'Hambantota': 103, 'Chester-le-Street': 73, 'ICCA Dubai': 109, 'Canberra': 66, 'Port of Spain': 158, 'Nagpur': 142, 'Sydney': 175, 'The Oval': 179, 'Visakhapatnam': 184, 'Jamshedpur': 112, 'Dambulla': 80, 'Melbourne (Docklands)': 134, 'Fatullah': 94, 'Bengaluru': 56, 'Bulawayo': 64, 'Gujranwala': 100, 'Manchester': 131, 'Nairobi (Ruaraka)': 146, 'Rawalpindi': 165, 'Bogra': 60, 'Darwin': 81, 'Whangarei': 186, 'Mombasa': 136, 'Hobart': 106, 'Pallekele': 152, 'Roseau': 166, 'Cairns': 65, 'Vadodara': 182, 'Auckland': 52, 'Galle': 95, 'Chittagong': 74, 'Indore': 110, 'Kwekwe': 126, 'Kuala Lumpur': 125, 'Mount Maunganui': 138, 'Kandy': 115, 'Aberdeen': 47, 'Port Moresby': 157, 'Southampton': 172, 'East London': 90, 'Chandigarh': 71, 'Nairobi (Gym)': 144, 'Dublin (Malahide)': 87, 'Nairobi': 143, 'Gwalior': 102, 'Cuttack': 79, 'Melbourne': 133, 'Perth': 153, 'Faisalabad': 92, 'Schiedam': 168, "Lord's": 130, 'Peshawar': 154, 'Hyderabad (Deccan)': 107, 'Rotterdam': 167, 'Port Elizabeth': 156, 'The Hague': 178, 'Dubai (DSC)': 85, 'Colombo (PSS)': 76, 'Hyderabad (Sind)': 108, 'Nairobi (Jaff)': 145, 'Karachi': 117, 'Dhaka': 83, 'Birmingham': 58, 'Bridgetown': 61, 'Nelson': 148, 'Mong Kok': 137, 'Mumbai': 140, 'Leeds': 128, 'Mumbai (BS)': 141, 'Providence': 160, 'Pietermaritzburg': 155, 'Adelaide': 49, 'Kolkata': 124, 'Nottingham': 150, 'Bloemfontein': 59, 'North Sound': 149, 'Lahore': 127, 'Kimberley': 119, 'Cape Town': 68, 'Chennai': 72, 'Jodhpur': 113, 'Sheikhupura': 170, 'Durban': 89, 'Cardiff': 69, 'Sharjah': 169, 'Dunedin': 88, 'Potchefstroom': 159, 'Kanpur': 116, 'Queenstown': 162, 'Guwahati': 101, 'Taupo': 177, 'Colombo (SSC)': 78, 'Brisbane': 62, 'King City (NW)': 120}



{'1': 187, '2': 188}

In [13]:
#Hash Indexing the Target Winners

winnerIndex = {}
counter = 0
for i,teams in enumerate(list(match_data.columns)):
    if i<189:
        continue
    
    teamName = str(teams)
    teamName = teamName.split("Winner_", 1)[-1]
    winnerIndex[teamName] = counter
    counter+=1
print(winnerIndex)

{'Australia': 3, 'Scotland': 17, 'Canada': 6, 'Bermuda': 5, 'West Indies': 21, 'ICC World XI': 9, 'England': 7, 'Bangladesh': 4, 'Africa XI': 1, 'India': 10, 'Asia XI': 2, 'South Africa': 18, 'Ireland': 11, 'no result': 23, 'tied': 24, 'Afghanistan': 0, 'Pakistan': 16, 'Netherlands': 13, 'Zimbabwe': 22, 'New Zealand': 14, 'U.A.E.': 20, 'Hong Kong': 8, 'Kenya': 12, 'P.N.G.': 15, 'Sri Lanka': 19}

In [17]:
#Running Prediction in Detailed Manner

inputPrediction = [0]*189
#print(inputPrediction)
t1 = 'India'
t2 = 'Pakistan'
ground = 'Mumbai'
innings = '1'
inputPrediction[ourTeams_1[t1]] = 1
inputPrediction[ourTeams_2[t2]] = 1
inputPrediction[ourGrounds[ground]] = 1
inputPrediction[ourInnings[innings]] = 1
#print(inputPrediction)
print("\n\n\n")

#Running Predictions

ourPrediction = DTclf1.predict([inputPrediction])
print(ourPrediction)
ourProb = DTclf1.proba([inputPrediction])
print(ourProb)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.
   0.  0.  0.  0.  0.  0.  0.]]

AttributeError: 'DecisionTreeClassifier' object has no attribute 'proba'